name: Daily Export
on:
  schedule:
    - cron: '0 11 * * *'
jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - name: Send /export command
        run: curl -X POST "https://api.telegram.org/bot8475571525:AAHBl4R9qYPiK9hBtRAPQV-qZWxqwfOn6N4/sendMessage?chat_id=8475571525&text=/export"
        
